## STAGE ONE ##

# Based on node server version 15
FROM node:15 as build
# Working directory
WORKDIR '/app'
# Copy project dependencies into WORKDIR
COPY package.json .
# Install packages
RUN npm install
# Copy the rest of the code
COPY . .
# Build project for production
RUN npm run build

## STAGE TWO ##

# Based on nginx server version 1.22.1
FROM nginx:1.22.1 as server
# Copy build files
COPY --from=build /app/build /usr/share/nginx/html






