version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: reactgreenit
    container_name: react-nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./src:/app/src